In [2]:
import torch
x = torch.arange(20)
x
X = x.reshape(4,5)
print(X)


tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


In [8]:
x = torch.arange(20).reshape(4,5)
y = x.clone()

print(x * y)  # 两个元素按照元素相乘

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361]])


In [2]:
torch.randn(3, 4)

tensor([[ 0.3583, -0.7973, -0.0337, -1.1273],
        [-0.2637,  0.9098, -1.7170, -0.2237],
        [ 0.8051, -0.7207, -1.2479, -1.2114]])

In [11]:
x = torch.arange(10).reshape(5,1,2)
x

tensor([[[0, 1]],

        [[2, 3]],

        [[4, 5]],

        [[6, 7]],

        [[8, 9]]])

In [12]:
y = torch.arange(10).reshape(5,2,1)
y

tensor([[[0],
         [1]],

        [[2],
         [3]],

        [[4],
         [5]],

        [[6],
         [7]],

        [[8],
         [9]]])

In [14]:
x = torch.arange(20.*2.).reshape(2,4,5)
x

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]]])

In [18]:
x1 = x.sum(axis=0)
x2 = x.sum(axis = 1)
x3 = x.sum(axis= 2)
x4 = x.sum(axis = [0, 1])
print(x1, x1.shape)
print(x2, x2.shape)
print(x3, x3.shape)
print(x4, x4.shape)

tensor([[20., 22., 24., 26., 28.],
        [30., 32., 34., 36., 38.],
        [40., 42., 44., 46., 48.],
        [50., 52., 54., 56., 58.]]) torch.Size([4, 5])
tensor([[ 30.,  34.,  38.,  42.,  46.],
        [110., 114., 118., 122., 126.]]) torch.Size([2, 5])
tensor([[ 10.,  35.,  60.,  85.],
        [110., 135., 160., 185.]]) torch.Size([2, 4])
tensor([140., 148., 156., 164., 172.]) torch.Size([5])


In [20]:
x = torch.arange(20.).reshape(4,5)
print(x)
print(x[1:2, :])

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]])
tensor([[5., 6., 7., 8., 9.]])


# 自动求导


In [4]:
x = torch.empty(5,3)
print(x)

tensor([[9.2755e-39, 1.0561e-38, 6.9796e-39],
        [1.0102e-38, 1.0837e-38, 8.4490e-39],
        [9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39]])


In [6]:
x = torch.rand(5,3)
print(x)

tensor([[0.0733, 0.5606, 0.8321],
        [0.0723, 0.0366, 0.7327],
        [0.5760, 0.6700, 0.1349],
        [0.5027, 0.7890, 0.6708],
        [0.5463, 0.4957, 0.3598]])


In [7]:
x = torch.randn(2,3)
x

tensor([[ 0.7766, -0.4660, -0.1284],
        [ 0.4474,  0.6835, -0.3732]])

In [18]:
a = torch.tensor([1., 2.])
a.data
a.grad
a.requires_grad
a.requires_grad_()
a.requires_grad_()

tensor([1., 2.], requires_grad=True)