In [26]:
import torch
from d2l import torch as d2l


In [27]:

def corr2d_multi_in(X, K):
    # 先遍历“X”和“K”的第0个维度（通道维度），再把它们加在一起
    # zip 操作会把最外面那一纬度做做遍历，打包起来
    return sum(d2l.corr2d(x, k) for x, k in zip(X, K))

In [28]:
# 测试
A = torch.rand(3,3,3)
print(A)
B = torch.rand(3)
print(B)

for x,y in zip(A, B):
    print(x,y)

tensor([[[0.5595, 0.2569, 0.3188],
         [0.8882, 0.1906, 0.4419],
         [0.7539, 0.7017, 0.8537]],

        [[0.0302, 0.5844, 0.1255],
         [0.5419, 0.2763, 0.7581],
         [0.4671, 0.1377, 0.0397]],

        [[0.3036, 0.2139, 0.2762],
         [0.3462, 0.4842, 0.4218],
         [0.4368, 0.5055, 0.9141]]])
tensor([0.8778, 0.4963, 0.3077])
tensor([[0.5595, 0.2569, 0.3188],
        [0.8882, 0.1906, 0.4419],
        [0.7539, 0.7017, 0.8537]]) tensor(0.8778)
tensor([[0.0302, 0.5844, 0.1255],
        [0.5419, 0.2763, 0.7581],
        [0.4671, 0.1377, 0.0397]]) tensor(0.4963)
tensor([[0.3036, 0.2139, 0.2762],
        [0.3462, 0.4842, 0.4218],
        [0.4368, 0.5055, 0.9141]]) tensor(0.3077)


In [29]:
# 测试
T1 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(T1.shape)
T2 = torch.tensor([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
print(T2.shape)

T3 = torch.stack((T1, T2), dim=0)
print(T3, T3.shape, "\n")

T4 = torch.stack((T1, T2), dim=1)
print(T4, T4.shape,"\n")

T5 = torch.stack((T1, T2), dim=2)
print(T5, T5.shape)

torch.Size([3, 3])
torch.Size([3, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]]) torch.Size([2, 3, 3]) 

tensor([[[ 1,  2,  3],
         [10, 20, 30]],

        [[ 4,  5,  6],
         [40, 50, 60]],

        [[ 7,  8,  9],
         [70, 80, 90]]]) torch.Size([3, 2, 3]) 

tensor([[[ 1, 10],
         [ 2, 20],
         [ 3, 30]],

        [[ 4, 40],
         [ 5, 50],
         [ 6, 60]],

        [[ 7, 70],
         [ 8, 80],
         [ 9, 90]]]) torch.Size([3, 3, 2])


In [30]:
# 2个3*3的图像通道
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
               [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])
print(X.shape)
# 2个2*2的卷积核
# [[0.0, 1.0], [2.0, 3.0]] 与  [[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]]做卷积运算
# [[1.0, 2.0], [3.0, 4.0]] 与 [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]] 做卷积运算
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])
print(K.shape)

corr2d_multi_in(X, K)

torch.Size([2, 3, 3])
torch.Size([2, 2, 2])


tensor([[ 56.,  72.],
        [104., 120.]])

In [31]:
# 多输出通道
# X还是3维的 K是4维的 最高的那一维度是卷积核的组数，剩下的那3维是指给输入图像的每一个通道都单独分配一个卷积核
def corr2d_multi_in_out(X, K):
    # 迭代“K”的第0个维度，每次都对输入“X”执行互相关运算。
    # 最后将所有结果都叠加在一起
    return torch.stack([corr2d_multi_in(X, k) for k in K], 0)
    

In [32]:
K = torch.stack((K, K + 1, K + 2), 0)
K.shape

torch.Size([3, 2, 2, 2])

In [33]:
corr2d_multi_in_out(X, K)

tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])